name: FUCKING RING CAMERA FEED
version: "1.1.7"
slug: ringlivestream
maintainer: DanGroverUK
description: Live stream Ring cameras via ring-client-api + ffmpeg (on-demand)
arch:
  - aarch64
  - amd64
  - armv7
startup: application
url: https://github.com/DanGroverUK/ring-hassio
boot: manual
init: false
ingress: false
homeassistant_api: true
hassio_api: true
auth_api: true
hassio_role: manager
panel_icon: mdi:video
ports:
  8080/tcp: 8080
map:
  - type: addons
    read_only: false
  - type: addon_config
    read_only: false
  - type: ssl
    read_only: false
  - type: share
    read_only: false
  - type: homeassistant_config
    read_only: false
  - type: backup
    read_only: false
  - type: media
    read_only: false
  - type: data
    read_only: false

options:
  ring_refresh_token: ""
  camera_name: ""
  stream_quality: "high" # low|medium|high
  video_codec: "auto" # auto|copy|h264_v4l2m2m|h264
  hwaccel: "auto" # auto|none
  port: 8080
  debug: false

  # NEW: HA event/state integration
  ha_integration: true # enable/disable HA API calls
  ha_entity_id: "binary_sensor.ring_livestream_playing"
  ha_event_prefix: "ring_livestream" # -> ring_livestream_started / ring_livestream_stopped
schema:
  ring_refresh_token: str
  camera_name: str
  stream_quality: list(low|medium|high)?
  video_codec: list(auto|copy|h264_v4l2m2m|h264)?
  hwaccel: list(auto|none)?
  port: int?
  debug: bool?
  ha_integration: bool?
  ha_entity_id: str?
  ha_event_prefix: str?
